### pobranie danych meta wybranego zdjęcia potrzebnych do jego obróbki (width,height)
GET http://localhost:3000/api/filters/metadata/1711195846469

### użycie konkretnego filtra, dane o nim przekazujemy w jsonie
PATCH http://localhost:3000/api/filters

{"id":1711195846469,"lastChange":"rotate"}

### pobranie pliku zdjęcia (nie jsona zdjęcia) wg ida
GET http://localhost:3000/api/getimage/1681671564412

### pobranie pliku przefiltrowanego zdjęcia (nie jsona zdjęcia) wg id i nazwy filtra
GET http://localhost:3000/api/getimage/1681671564412/filter/tint