### pobranie danych meta wybranego zdjęcia potrzebnych do jego obróbki (width,height)
GET http://localhost:3000/api/filters/metadata/1716839671693

### użycie konkretnego filtra, dane o nim przekazujemy w jsonie
PATCH http://localhost:3000/api/filters

{"id":1716845608944,"lastChange":"rotate"}

### pobranie pliku zdjęcia (nie jsona zdjęcia) wg ida
GET http://localhost:3000/api/filters/getimage/1716839671692

### pobranie pliku przefiltrowanego zdjęcia (nie jsona zdjęcia) wg id i nazwy filtra
GET http://localhost:3000/api/getimage/1716793053286/filter/tint