### register usera
POST http://localhost:3000/api/user/register HTTP/1.1
content-type: application/json

{"name":"name","lastName":"lastName","email":"name@email.pl","password":"password"}

### user potwierdza rejestrację konta z użyciem tokena
GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwucGwiLCJhbnlPdGhlckRhdGEiOiJwYXNzd29yZCIsImlhdCI6MTcxNzI2NTQzOCwiZXhwIjoxNzE3MjY1NzM4fQ.lkgJ3_JQVu8s3PSWQA4pbKJV3VDhlBJjlwveAVu8IFQ

### logowanie z odesłaniem tokena po zalogowaniu - od tej pory każde żądanie zasobów ma zawierać token
POST http://localhost:3000/api/user/login

{"email":"name@email.pl","password":"password"}

### get json all users - funkcja pomocnicza dla testów zarejestrowanych userów
GET http://localhost:3000/api/user